<?php
namespace T3docs\RestructuredApiTools\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use T3docs\RestructuredApiTools\Util\ClassDocsHelper;

class PhpDomainCommand extends Command
{
    /**
     * Configure the command by defining the name, options and arguments
     */
    protected function configure()
    {
        $this->setHelp('Prints a list of recent sys_log entries.'
            . LF . 'If you want to get more detailed information, use the --verbose option.')
            ->setDescription('Run content importer. Without '
                . ' arguments all available wizards will be run.')
            ->addArgument(
                'wizardName',
                InputArgument::OPTIONAL,
                'Here is a description for your argument'
            )
            ->addOption(
                'brute-force',
                'b',
                InputOption::VALUE_OPTIONAL,
                'Some optional option for your wizard(s). You '
                . 'can use --brute-force or -b when running command'
            );
    }

    /**
     * Executes the command for showing sys_log entries
     *
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int error code
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $io = new SymfonyStyle($input, $output);
        $io->title($this->getDescription());

        $output = ClassDocsHelper::extractDocsFromClass('\TYPO3\CMS\Backend\Module\ModuleInterface');
        // ...
        $io->writeln('.. Generated by https://github.com/linawolf/t3docs_restructured_api_tools ' . LF . $output);
        return Command::SUCCESS;
    }
}
